artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://files.consumerfinance.gov/ccdb/complaints.csv.zip
  local_data_file: artifacts/data_ingestion/complaints.csv.zip
  unzip_dir: artifacts/data_ingestion
  csv_file_path: artifacts/data_ingestion/complaints.csv

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/model.pt

prepare_callbacks:
  root_dir: artifacts/prepare_callbacks
  tensorboard_root_log_dir: artifacts/prepare_callbacks/tensorboard_log_dir
  checkpoint_model_filepath: artifacts/prepare_callbacks/checkpoint_dir/model.pt

training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.pt